# Generated by Django 4.0.5 on 2022-12-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('barcode_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('barcode_name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'barcodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=45)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Order',
            fields=[
                ('client_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('sizex', models.IntegerField(blank=True, null=True)),
                ('sizey', models.IntegerField(blank=True, null=True)),
                ('sizez', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'client_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Routes',
            fields=[
                ('client_route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'client_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liked', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlPoints',
            fields=[
                ('control_points_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'control_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('premise_id', models.AutoField(primary_key=True, serialize=False)),
                ('coord_long', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('email', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
            ],
            options={
                'db_table': 'premises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiseType',
            fields=[
                ('premise_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_decryp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'premise_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier_Order',
            fields=[
                ('supplier_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'supplier_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier_Routes',
            fields=[
                ('supplier_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goodslist',
            fields=[
                ('goodslist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Supp_ord.premises')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Supp_ord.products')),
            ],
        ),
    ]
