# Generated by Django 4.1.2 on 2022-10-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalog_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
    ]
