# Generated by Django 4.1.2 on 2022-11-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0003_clients_region'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
