# Generated by Django 4.1.2 on 2022-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0004_alter_clients_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=45)),
                ('LName', models.CharField(max_length=45)),
                ('Patronymic', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premise_type',
            fields=[
                ('premise_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_decryp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'premise_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('premise_id', models.AutoField(primary_key=True, serialize=False)),
                ('coord_long', models.FloatField()),
                ('coord_lat', models.FloatField()),
                ('email', models.CharField(max_length=45)),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
            ],
            options={
                'db_table': 'premises',
                'managed': False,
            },
        ),
    ]
