# Generated by Django 4.1.2 on 2022-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0005_employees_premise_type_premises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('premise_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_decryp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'premise_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Premise_type',
        ),
    ]
