# Generated by Django 4.1.2 on 2022-11-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0006_pre_delete_premise_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pre',
            table='premises_type',
        ),
    ]
