# Generated by Django 4.1.2 on 2022-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0007_alter_pre_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premise_type',
            fields=[
                ('premise_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_decryp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'premise_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pre',
        ),
    ]
