# Generated by Django 4.1.2 on 2022-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0008_premise_type_delete_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients_order',
            fields=[
                ('clients_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Control_points',
            fields=[
                ('control_points_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name=())),
            ],
            options={
                'db_table': 'control_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('website', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goodslist',
            fields=[
                ('goodslist_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'goodslist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('barcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=45)),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier_order',
            fields=[
                ('supplier_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('recieved_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'supplier_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('postcode', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('h_number', models.IntegerField()),
                ('website', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
    ]
