# Generated by Django 4.1.2 on 2022-11-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0009_actions_clients_order_control_points_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers_Client_order',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('transfer_type', models.BooleanField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'transfers_client_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers_Supplier_order',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('transfer_type', models.BooleanField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'transfers_supplier_order',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
    ]
