# Generated by Django 4.1.2 on 2022-11-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0010_transfers_client_order_transfers_supplier_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_routes',
            fields=[
                ('client_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'client_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier_routes',
            fields=[
                ('supplier_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier_routes',
                'managed': False,
            },
        ),
    ]
