# Generated by Django 4.1.2 on 2022-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0011_client_routes_supplier_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_order',
            fields=[
                ('clients_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('sizex', models.IntegerField()),
                ('sizey', models.IntegerField()),
                ('sizez', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'client_order',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Clients_order',
        ),
        migrations.DeleteModel(
            name='Transfers_Client_order',
        ),
        migrations.DeleteModel(
            name='Transfers_Supplier_order',
        ),
    ]
