# Generated by Django 4.1.2 on 2022-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0012_client_order_delete_clients_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('barcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'barcodes',
                'managed': False,
            },
        ),
    ]
