# Generated by Django 4.1.2 on 2022-12-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0014_ans_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodslist',
            options={},
        ),
    ]
