# Generated by Django 4.1.2 on 2022-12-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supp_ord', '0015_alter_goodslist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='premise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Supp_ord.premises'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodslist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Supp_ord.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='goodslist_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='goodslist',
            table=None,
        ),
    ]
